// Til sozlamalari
const languages = {
  uz: {
    welcome: "🎉 Xush kelibsiz!\n\nSlotkayaSloboda botiga xush kelibsiz!\nTilni tanlang:",
    language_selected: "✅ Til tanlandi: O'zbekcha",
    register: "📝 Ro'yhatdan o'tish",
    help: "📞 Yordam",
    enter_name: "👤 Ismingizni kiriting:",
    enter_shop: "🏪 Do'kon nomini kiriting:",
    enter_phone: "📱 Telefon raqamingizni kiriting:\n(Masalan: +998901234567)",
    enter_region: "🏛 Viloyatingizni kiriting:\n(Masalan: Xorazm)",
    enter_district: "🏘 Tuman/Shaharingizni kiriting:\n(Masalan: Urganch)",
    enter_location: "📍 Do'kon joylashuvini yuboring:",
    location_button: "📍 Joylashuvni yuborish",
    registration_success: "✅ Ro'yhatdan muvaffaqiyatli o'tdingiz!",
    order_now: "🛍 Buyurtma berish",
    my_orders: "📦 Buyurtmalarim",
    settings: "⚙️ Sozlamalar",
    my_shop_management: "🏪 Mening do'konim boshqaruvi",
    company_management: "🏢 Firma boshqaruvi",
    delivery_service: "🚚 Yetkazib berish",
    products: "📦 Mahsulotlar",
    debt_status: "💳 Qarz holati",
    statistics: "📊 Statistika",
    support: "📞 Yordam",
    orders: "📋 Buyurtmalar",
    drivers: "🚚 Haydovchilar",
    customers: "👥 Mijozlar",
    admin_panel: "👨‍💼 Admin Panel",
    driver_panel: "🚚 Haydovchi Panel",
    shop_panel: "🏪 Do'kon Panel"
  },
  uzc: {
    welcome: "🎉 Хуш келибсиз!\n\nSlotkayaSloboda ботига хуш келибсиз!\nТилни танланг:",
    language_selected: "✅ Тил танланди: Ўзбекча",
    register: "📝 Рўйхатдан ўтиш",
    help: "📞 Ёрдам",
    enter_name: "👤 Исмингизни киритинг:",
    enter_shop: "🏪 Дўкон номини киритинг:",
    enter_phone: "📱 Телефон рақамингизни киритинг:\n(Масалан: +998901234567)",
    enter_location: "📍 Дўкон жойлашувини юборинг:",
    location_button: "📍 Жойлашувни юбориш",
    registration_success: "✅ Рўйхатдан муваффақиятли ўтдингиз!",
    order_now: "🛍 Буюртма бериш",
    my_orders: "📦 Буюртмаларим",
    settings: "⚙️ Созламалар",
    my_shop_management: "🏪 Менинг дўконим бошқаруви",
    company_management: "🏢 Фирма бошқаруви",
    delivery_service: "🚚 Етказиб бериш",
    products: "📦 Махсулотлар",
    debt_status: "💳 Қарз холати",
    statistics: "📊 Статистика",
    support: "📞 Ёрдам",
    orders: "📋 Буюртмалар",
    drivers: "🚚 Хайдовчилар",
    customers: "👥 Мижозлар",
    admin_panel: "👨‍💼 Админ Панел",
    driver_panel: "🚚 Хайдовчи Панел",
    shop_panel: "🏪 Дўкон Панел"
  },
  ru: {
    welcome: "🎉 Добро пожаловать!\n\nДобро пожаловать в SlotkayaSloboda бот!\nВыберите язык:",
    language_selected: "✅ Язык выбран: Русский",
    register: "📝 Регистрация",
    help: "📞 Помощь",
    enter_name: "👤 Введите ваше имя:",
    enter_shop: "🏪 Введите название магазина:",
    enter_phone: "📱 Введите номер телефона:\n(Например: +998901234567)",
    enter_location: "📍 Отправьте местоположение магазина:",
    location_button: "📍 Отправить местоположение",
    registration_success: "✅ Регистрация прошла успешно!",
    order_now: "🛍 Сделать заказ",
    my_orders: "📦 Мои заказы",
    settings: "⚙️ Настройки",
    my_shop_management: "🏪 Управление моим магазином",
    company_management: "🏢 Управление компанией",
    delivery_service: "🚚 Доставка",
    products: "📦 Товары",
    debt_status: "💳 Состояние долга",
    statistics: "📊 Статистика",
    support: "📞 Поддержка",
    orders: "📋 Заказы",
    drivers: "🚚 Водители",
    customers: "👥 Клиенты",
    admin_panel: "👨‍💼 Админ Панель",
    driver_panel: "🚚 Панель Водителя",
    shop_panel: "🏪 Панель Магазина"
  }
};

module.exports = languages;